repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0 # Use the latest revision
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: debug-statements
      - id: detect-private-key
      - id: requirements-txt-fixer
